//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomAllocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllocate
    {
        public int RId { get; set; }
        public string RoomName { get; set; }
        public string Sub { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    }
}
